name: Add issue to project
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    steps:
      - name: Print issue creator
        run: echo ${{ github.event.issue.user.login }}
      - name: Do something
        if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened') && github.event.issue.user.login != 'renovate[bot]'
        run: echo issue opened/reopened by ${{ github.event.issue.user.login }}
