name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        # Fix the version by using a commit sha
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GH_CQ_BOT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: ok-to-test
          named-args: true
          permission: write
