name: Renovate
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/15 * * * *"
  pull_request:
    branches:
      - main
      - chore/add_renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.37.0
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.GH_CQ_BOT }}
