name: Renovate
on:
  schedule:
    - cron: "0/15 * * * *"
  pull_request:
    branches:
      - main
      - chore/add_renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.0.1
        env:
          RENOVATE_TOKEN: ${{ secrets.GH_CQ_BOT }}
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.GH_CQ_BOT }}
