name: Test workflow
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [manual-approve-command]
  pull_request_target:
    branches:
      - main

jobs:
  manually_approved:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.manually_approved.outputs.result }}
    steps:
      - name: Check if was approved manually
        id: manually_approved
        run: |
          manually_approved=${{ github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha != '' && contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha) }}
          echo ::set-output name=result::"$manually_approved"
  is_organization_member:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.is_organization_member.outputs.result }}
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: yevgenypats/is-organization-member@646ee210c04d55d8b7f3a591722d06eb16310236
        with:
          organization: cloudquery
          username: ${{ github.actor }}
          token: ${{ secrets.GH_PAT }}

  # This is here so we can enforce branch protection required status check
  ok_to_test:
    needs: [is_organization_member, manually_approved]
    runs-on: ubuntu-latest
    if: needs.is_organization_member.outputs.status == 'true' || needs.manually_approved.outputs.status == 'true'
    outputs:
      status: ${{ steps.ok_to_test.outputs.result }}
    steps:
      - name: Check if ok to test
        id: ok_to_test
        run: |
          echo ::set-output name=result::"true"

  lint_doc:
    needs: [ok_to_test]
    runs-on: ubuntu-latest
    steps:
      - name: Fork based /ok-to-test checkout
        uses: actions/checkout@v3
        if: github.event_name == 'repository_dispatch'
        with:
          ref: "refs/pull/${{ github.event.client_payload.pull_request.number }}/merge"
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '!(ignore/**/*)'
      - name: Set up Go 1.x
        if: steps.changes.outputs.src == 'true'
        run: echo "Hello World"
        id: last_step

      - uses: actions/github-script@v6
        id: update-check-run
        if: ${{ always() && github.event_name == 'repository_dispatch' }}
        env:
          conclusion: ${{ job.status }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pull } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.event.client_payload.pull_request.number
            });
            const ref = pull.head.sha;
            const { data: checks } = await github.rest.checks.listForRef({
              ...context.repo,
              ref
            });
            const check = checks.check_runs.filter(c => c.name === context.job);
            const { data: result } = await github.rest.checks.update({
              ...context.repo,
              check_run_id: check[0].id,
              status: 'completed',
              conclusion: process.env.conclusion
            });
            return result;
